name: Update Requirements

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write  # <-- This grants write permissions

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures all history is fetched

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pip and any other tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools

      - name: Update requirements.txt
        run: |
          if [ -f requirements.in ]; then
            pip-compile --output-file requirements.txt requirements.in
          else
            pip freeze > requirements.txt
          fi

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b update-requirements  # Create a new branch
          git add requirements.txt
          git commit -m "chore: Updated requirements.txt" || echo "No changes to commit"
          git push origin update-requirements || echo "Push failed, check permissions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This is required for authentication
