name: Update Requirements

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write  # Required to push changes

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pip and dependencies
        run: |
          python -m pip install --upgrade pip pip-tools

      - name: Upgrade packages in requirements.txt
        run: |
          pip install -r requirements.txt --upgrade
          pip freeze > requirements.txt

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b update-requirements  # Create a new branch
          git add requirements.txt
          git commit -m "chore: Auto-update requirements.txt" || echo "No changes to commit"
          git push origin update-requirements || echo "Push failed, check permissions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Authenticate using GitHub Token
